// Static manifest of all agents in the system.
// In Fase 2 this will be replaced by a DB-driven config (agent_configs table)
// so the back office can edit prompts/models without redeploy.

export type AgentMeta = {
  name: string
  displayName: string
  description: string
  model: string
  maxTokens: number
  category: 'orchestration' | 'pipeline' | 'modifier' | 'background' | 'utility'
  inputs: string[]
  outputs: string[]
  systemPromptPreview: string
  filePath: string
  enabled: boolean
  rules?: string[]  // Regole operative visibili in back office (read-only)
}

export const AGENTS_MANIFEST: AgentMeta[] = [
  {
    name: 'clarifier',
    displayName: 'Clarifier',
    description: 'Analizza la richiesta utente e, se ambigua, fa domande prima di avviare la pipeline. Evita assunzioni errate su lingua, business type ecc.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 512,
    category: 'orchestration',
    inputs: ['user request', 'existing pages', 'project context'],
    outputs: ['proceed: true | questions string'],
    systemPromptPreview: 'Decidi se la richiesta è chiara o se mancano info critiche. Chiedi solo in 2 casi: business type ambiguo su prima run, lingua non deducibile.',
    filePath: 'lib/agents/clarifier.ts',
    enabled: true,
    rules: [
      'Gira solo su pipeline (non su html/seo/design-update/content-update)',
      'Chiede solo se business type completamente assente o lingua non deducibile su prima run',
      'Con pagine esistenti: procede sempre senza chiedere',
      'In caso di errore o dubbio → procede (mai bloccare inutilmente)',
      'Max 2 domande alla volta, tono amichevole, in italiano',
    ],
  },
  {
    name: 'orchestrator',
    displayName: 'Orchestrator',
    description: 'Classifica il messaggio utente e instrada a pipeline (crea sito) o html (modifica puntuale). Zero LLM — logica rule-based pura.',
    model: 'rule-based',
    maxTokens: 0,
    category: 'orchestration',
    inputs: ['user message', 'page count', 'hasImages', 'hasInspirationUrl'],
    outputs: ['agent: "pipeline" | "html"'],
    systemPromptPreview: 'Keyword-based classification: inspiration+screenshots → pipeline; empty site → pipeline; existing pages + modification → html.',
    filePath: 'lib/agents/orchestrator.ts',
    enabled: true,
    rules: [
      '🔴 ZERO LLM: logica rule-based pura, nessuna API call',
      '↳ Pipeline (create site): se pages=0, o (inspirationUrl + attachedImages), o keywords creazione',
      '↳ HTML (modify): se pages>0 e keyword modifica',
      '↳ Default fallback: html (modifica puntuale più sicura)',
    ],
  },
  {
    name: 'memory',
    displayName: 'Memory Agent',
    description: 'Mantiene il contesto del progetto tra le conversazioni (business type, target, tone of voice).',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 2048,
    category: 'background',
    inputs: ['conversation history', 'existing context'],
    outputs: ['updated project context'],
    systemPromptPreview: 'Estrai informazioni chiave sul progetto dell\'utente (settore, target, tono) e aggiorna il contesto persistente.',
    filePath: 'lib/agents/memory-agent.ts',
    enabled: true,
    rules: [
      'Gira in background ad ogni messaggio, non blocca la pipeline',
      'Estrae: business type, target audience, tone of voice, preferenze di stile',
      'Non genera HTML, solo aggiorna il contesto JSON del progetto',
      'Il contesto prodotto viene passato a tutti gli altri agenti',
    ],
  },
  {
    name: 'planner',
    displayName: 'Planner',
    description: 'Pianifica la struttura del sito: pagine, sezioni, business type detection.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'pipeline',
    inputs: ['user request', 'existing pages'],
    outputs: ['site plan (pages + sections)'],
    systemPromptPreview: 'Genera un piano del sito multi-pagina con sezioni per pagina, identificando il business type.',
    filePath: 'lib/agents/planner.ts',
    enabled: true,
    rules: [
      '🔴 Prima run (nessuna pagina esistente): genera SOLO la pagina "home"',
      '🏠 Struttura home obbligatoria: hero → features (max 3) → CTA → footer',
      'Run successive: può suggerire pagine aggiuntive (about, contact, ecc.) se pertinenti',
      'Identifica sempre il business type (ristorante, studio, e-commerce, ecc.)',
      'Non genera HTML, solo il piano strutturale che passa a Content e Design',
    ],
  },
  {
    name: 'content',
    displayName: 'Content Agent',
    description: 'Genera i contenuti testuali per ogni pagina del piano: title, meta, h1, sezioni, schema.org.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 8192,
    category: 'pipeline',
    inputs: ['plan', 'context', 'language'],
    outputs: ['ContentOutput.pages'],
    systemPromptPreview: 'Scrivi contenuti SEO-friendly nella lingua specificata, con tone of voice coerente al contesto.',
    filePath: 'lib/agents/content-agent.ts',
    enabled: true,
    rules: [
      'Scrive nella lingua rilevata dal messaggio utente (auto-detect)',
      'Genera: title, meta description, h1, testo sezioni, CTA label, schema.org JSON-LD',
      'Usa il tone of voice dal contesto Memory Agent (se disponibile)',
      'Non genera CSS o layout, solo testi',
      'Produce JSON strutturato, non HTML',
    ],
  },
  {
    name: 'design',
    displayName: 'Design Agent',
    description: 'Genera design tokens (colori, font), CSS e brief di stile. Può ricevere brief di ispirazione da siti analizzati.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'pipeline',
    inputs: ['plan', 'context', 'inspirationBriefs'],
    outputs: ['DesignOutput (tokens + css + fontsUrl)'],
    systemPromptPreview: 'Crea un design system coerente con il business type, includendo palette colori, tipografia, e CSS base.',
    filePath: 'lib/agents/design-agent.ts',
    enabled: true,
    rules: [
      'Genera palette colori coerente con il business type (es: ristorante → caldi, studio legale → sobri)',
      'Sceglie font Google da caricare via CDN (max 2 font: heading + body)',
      'Produce CSS custom properties (design tokens), non inline styles',
      'Se riceve inspirationBriefs da Site Analyzer, li usa come riferimento stilistico',
      'Non genera HTML o testi',
    ],
  },
  {
    name: 'html',
    displayName: 'HTML Agent',
    description: 'Genera o modifica HTML con quality feedback loop. Applica automaticamente le regole specifiche del progetto (link style, form endpoints, CSS approach).',
    model: 'claude-sonnet-4-6',
    maxTokens: 16384,
    category: 'pipeline',
    inputs: ['plan', 'content', 'design', 'project media library', 'pages attuali', 'projectRules (apprese dal progetto)'],
    outputs: ['pages HTML (con quality check + self-correction)'],
    systemPromptPreview: 'Genera HTML multi-pagina mobile-first rispettando le regole specifiche del progetto. Se critical issues, il sistema chiede di correggerle (max 1 retry).',
    filePath: 'lib/agents/html-agent.ts',
    enabled: true,
    rules: [
      '📋 Rispetta SEMPRE le PROJECT RULES (passate nel contesto) — sono apprese dal progetto stesso',
      '🔄 Quality feedback loop: se rilevati problemi critici (H1 count, absolute links, form endpoints), il sistema chiede di correggerli',
      '🚫 NON toccare MAI lo stile/CSS se non esplicitamente richiesto — aggiungi solo l\'elemento HTML richiesto usando classi già esistenti',
      '🎯 SCOPE minimo: dichiara nel campo "scope" solo le sezioni effettivamente modificate',
      '✅ Usa typed_edits per colori (css_var), font-size (css_prop), link href (attr), testi brevi (text)',
      'Output: HTML completo con <!DOCTYPE html>, <head> e <body>',
      'Mobile-first: viewport meta, layout responsive con CSS flexbox/grid',
      'Immagini: URL utente → media library → placeholder Unsplash',
      'Non usa framework esterni (React, Vue): solo HTML/CSS/JS vanilla',
      'Per le modifiche usa tool use: edit_page con operations/edits/typed_edits, add_page, delete_page',
    ],
  },
  {
    name: 'html-template',
    displayName: 'HTML Template Agent',
    description: 'Variante dell\'HTML agent che riempie un template HTML con placeholder {{key}} (es: template SaaS).',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 16384,
    category: 'pipeline',
    inputs: ['template html', 'plan', 'content', 'design'],
    outputs: ['template riempito'],
    systemPromptPreview: 'Sostituisci tutti i placeholder {{...}} con i contenuti forniti, adattando colori e font al design.',
    filePath: 'lib/agents/html-agent.ts',
    enabled: true,
  },
  {
    name: 'seo',
    displayName: 'SEO Agent',
    description: 'Genera sitemap.xml, robots.txt, ottimizza meta tags, Open Graph, canonical URLs.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'modifier',
    inputs: ['messages', 'pages', 'custom domain', 'context'],
    outputs: ['seo files + page edits'],
    systemPromptPreview: 'Ottimizza l\'aspetto SEO del sito: meta, sitemap, robots, schema.org, OG tags.',
    filePath: 'lib/agents/seo-agent.ts',
    enabled: true,
    rules: [
      'Agisce solo su richiesta esplicita SEO (non gira automaticamente nel pipeline base)',
      'Ottimizza: <title>, <meta description>, Open Graph, Twitter Card, canonical',
      'Genera sitemap.xml con tutte le pagine del sito',
      'Genera robots.txt con regole base',
      'Non modifica il layout o i testi visibili, solo i meta tag',
    ],
  },
  {
    name: 'design-update',
    displayName: 'Design Update Agent',
    description: 'Modifica solo aspetti di design (colori, font, tema) lasciando i contenuti invariati.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 8192,
    category: 'modifier',
    inputs: ['user request', 'pages attuali', 'context'],
    outputs: ['pages con design aggiornato'],
    systemPromptPreview: 'Cambia esclusivamente CSS/colori/tipografia senza modificare il testo del sito.',
    filePath: 'lib/agents/design-agent.ts',
    enabled: true,
    rules: [
      'Modifica SOLO CSS: colori, font, spaziatura, bordi, ombre',
      'Non tocca mai il testo visibile (h1, paragrafi, CTA label)',
      'Non aggiunge o rimuove sezioni o elementi HTML',
      'Usa find/replace per aggiornare solo le proprietà CSS cambiate',
    ],
  },
  {
    name: 'content-update',
    displayName: 'Content Update Agent',
    description: 'Riscrive i testi con tone of voice diverso o traduce, mantenendo il design invariato.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 8192,
    category: 'modifier',
    inputs: ['user request', 'pages attuali', 'context'],
    outputs: ['pages con testi aggiornati'],
    systemPromptPreview: 'Modifica solo i testi delle pagine secondo le istruzioni utente (tone, traduzione).',
    filePath: 'lib/agents/content-agent.ts',
    enabled: true,
    rules: [
      'Modifica SOLO i testi: headings, paragrafi, label CTA, alt text',
      'Non tocca mai CSS, classi, o struttura HTML',
      'Mantiene la stessa struttura semantica (h1 resta h1, ecc.)',
      'Può tradurre in un\'altra lingua se richiesto',
    ],
  },
  {
    name: 'site-analyzer',
    displayName: 'Site Analyzer',
    description: 'Analizza siti di ispirazione: estrae HTML/CSS da un URL (Round 1) e analizza gli screenshot caricati dall\'utente con Claude Vision (Round 2) per produrre un DesignBrief completo.',
    model: 'claude-sonnet-4-5-20250929',
    maxTokens: 2048,
    category: 'utility',
    inputs: ['URL', 'screenshot URLs (base64)'],
    outputs: ['DesignBrief (colors, fonts, style, spacing)'],
    systemPromptPreview: 'Visita un sito esterno (HTML/CSS) e/o analizza screenshot via Claude Vision. Produce un brief sintetico (palette, tipografia, layout) usabile come ispirazione.',
    filePath: 'lib/agents/site-analyzer.ts',
    enabled: true,
    rules: [
      'Round 1: fetch HTML del sito, estrae CSS inline + variabili custom (--primary, --font-*)',
      'Round 2: scarica gli screenshot caricati dall\'utente (max 4MB, jpeg/png/gif/webp) e li invia a Claude Vision',
      'Output: DesignBrief con colori HEX, font Google, border-radius, spacing, note di stile',
      'Non genera HTML, solo il brief — passa il risultato al Template Generator',
      'Se il fetch URL fallisce, prosegue solo con i screenshot (e viceversa)',
    ],
  },
  {
    name: 'template-generator',
    displayName: 'Template Generator',
    description: 'Genera un template HTML completo (con placeholder {{key}}) a partire dal DesignBrief estratto dal Site Analyzer. Usato nel flusso "ispirazione URL + screenshot".',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 16384,
    category: 'utility',
    inputs: ['DesignBrief', 'user request'],
    outputs: ['GeneratedTemplate (name, sector, 1 keyword EN, html)'],
    systemPromptPreview: 'Genera un template HTML professionale (~400 righe) che rispetta esattamente il design brief: colori, font, border-radius. Usa placeholder {{key}} per tutti i testi.',
    filePath: 'lib/agents/template-generator.ts',
    enabled: true,
    rules: [
      'Usa SEMPRE i colori e font del DesignBrief — mai inventare',
      'Tutti i testi sono placeholder {{key}} (mai testi fissi)',
      'Output min 400 righe: head + meta SEO, nav responsive, hero, features (3-4), CTA, footer',
      'Genera ESATTAMENTE 1 keyword in inglese (es: "hotel", "restaurant", "clinic")',
      'Il template generato viene salvato nella tabella templates di Supabase',
      'Nessuna dipendenza esterna eccetto Google Fonts e SVG inline',
    ],
  },
  {
    name: 'images',
    displayName: 'Images Agent',
    description: 'Ottimizza il markup delle immagini: alt text descrittivi, loading=lazy, srcset.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'utility',
    inputs: ['page html', 'business type'],
    outputs: ['edits find/replace per img'],
    systemPromptPreview: 'Migliora <img> aggiungendo alt SEO, loading=lazy, width/height. Non modificare src.',
    filePath: 'lib/agents/images-agent.ts',
    enabled: true,
    rules: [
      'Non modifica mai l\'attributo src delle immagini',
      'Aggiunge alt text descrittivo e SEO-friendly se mancante',
      'Aggiunge loading="lazy" a tutte le immagini non above-the-fold',
      'Aggiunge width e height se assenti (per prevenire layout shift)',
    ],
  },
  {
    name: 'accessibility',
    displayName: 'Accessibility Agent',
    description: 'Audit e correzioni accessibilità (WCAG): aria-labels, contrasto, struttura semantica.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'utility',
    inputs: ['page html'],
    outputs: ['edits per accessibility fixes'],
    systemPromptPreview: 'Audit WCAG: aggiungi aria-*, fix headings, contrasto, struttura semantica.',
    filePath: 'lib/agents/accessibility-agent.ts',
    enabled: true,
    rules: [
      'Standard di riferimento: WCAG 2.1 livello AA',
      'Controlla: gerarchia heading (h1→h2→h3), aria-label su bottoni, alt su immagini',
      'Aggiunge aria-*, role, tabindex dove necessario',
      'Non modifica il contenuto visibile o il layout',
    ],
  },
]

export const PIPELINE_FLOW = [
  { id: 'clarifier', label: 'Clarifier', column: 0, row: 0 },
  { id: 'memory', label: 'Memory', column: 1, row: 0 },
  { id: 'planner', label: 'Planner', column: 2, row: 0 },
  { id: 'site-analyzer', label: 'Site Analyzer\n(se URL)', column: 2, row: 1, optional: true },
  { id: 'content', label: 'Content', column: 3, row: 0 },
  { id: 'design', label: 'Design', column: 3, row: 1 },
  { id: 'html', label: 'HTML', column: 4, row: 0 },
] as const

export const PIPELINE_EDGES = [
  { from: 'clarifier', to: 'memory' },
  { from: 'memory', to: 'planner' },
  { from: 'planner', to: 'content' },
  { from: 'planner', to: 'design' },
  { from: 'site-analyzer', to: 'design' },
  { from: 'content', to: 'html' },
  { from: 'design', to: 'html' },
] as const
