// Static manifest of all agents in the system.
// In Fase 2 this will be replaced by a DB-driven config (agent_configs table)
// so the back office can edit prompts/models without redeploy.

export type AgentMeta = {
  name: string
  displayName: string
  description: string
  model: string
  maxTokens: number
  category: 'orchestration' | 'pipeline' | 'modifier' | 'background' | 'utility'
  inputs: string[]
  outputs: string[]
  systemPromptPreview: string
  filePath: string
  enabled: boolean
}

export const AGENTS_MANIFEST: AgentMeta[] = [
  {
    name: 'orchestrator',
    displayName: 'Orchestrator',
    description: 'Classifica il messaggio utente e instrada al pipeline o all\'agente appropriato (html, seo, design-update, content-update).',
    model: 'rule-based',
    maxTokens: 0,
    category: 'orchestration',
    inputs: ['user message', 'hasPages'],
    outputs: ['agent type'],
    systemPromptPreview: 'Regole keyword-based: CREATE_KEYWORDS → pipeline, SEO_KEYWORDS → seo, DESIGN_UPDATE_KEYWORDS → design-update, ecc.',
    filePath: 'lib/agents/orchestrator.ts',
    enabled: true,
  },
  {
    name: 'memory',
    displayName: 'Memory Agent',
    description: 'Mantiene il contesto del progetto tra le conversazioni (business type, target, tone of voice).',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 2048,
    category: 'background',
    inputs: ['conversation history', 'existing context'],
    outputs: ['updated project context'],
    systemPromptPreview: 'Estrai informazioni chiave sul progetto dell\'utente (settore, target, tono) e aggiorna il contesto persistente.',
    filePath: 'lib/agents/memory-agent.ts',
    enabled: true,
  },
  {
    name: 'planner',
    displayName: 'Planner',
    description: 'Pianifica la struttura del sito: pagine, sezioni, business type detection.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'pipeline',
    inputs: ['user request', 'existing pages'],
    outputs: ['site plan (pages + sections)'],
    systemPromptPreview: 'Genera un piano del sito multi-pagina con sezioni per pagina, identificando il business type.',
    filePath: 'lib/agents/planner.ts',
    enabled: true,
  },
  {
    name: 'content',
    displayName: 'Content Agent',
    description: 'Genera i contenuti testuali per ogni pagina del piano: title, meta, h1, sezioni, schema.org.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 8192,
    category: 'pipeline',
    inputs: ['plan', 'context', 'language'],
    outputs: ['ContentOutput.pages'],
    systemPromptPreview: 'Scrivi contenuti SEO-friendly nella lingua specificata, con tone of voice coerente al contesto.',
    filePath: 'lib/agents/content-agent.ts',
    enabled: true,
  },
  {
    name: 'design',
    displayName: 'Design Agent',
    description: 'Genera design tokens (colori, font), CSS e brief di stile. Può ricevere brief di ispirazione da siti analizzati.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'pipeline',
    inputs: ['plan', 'context', 'inspirationBriefs'],
    outputs: ['DesignOutput (tokens + css + fontsUrl)'],
    systemPromptPreview: 'Crea un design system coerente con il business type, includendo palette colori, tipografia, e CSS base.',
    filePath: 'lib/agents/design-agent.ts',
    enabled: true,
  },
  {
    name: 'html',
    displayName: 'HTML Agent',
    description: 'Genera o modifica HTML. Usato sia nel pipeline (create_site) sia per modifiche puntuali (edit_page, add_page, delete_page).',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 16384,
    category: 'pipeline',
    inputs: ['plan', 'content', 'design', 'project media library', 'pages attuali (per modifiche)'],
    outputs: ['pages HTML'],
    systemPromptPreview: 'Genera HTML multi-pagina mobile-first. Per le immagini segue gerarchia: URL utente → media library → placeholder.',
    filePath: 'lib/agents/html-agent.ts',
    enabled: true,
  },
  {
    name: 'html-template',
    displayName: 'HTML Template Agent',
    description: 'Variante dell\'HTML agent che riempie un template HTML con placeholder {{key}} (es: template SaaS).',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 16384,
    category: 'pipeline',
    inputs: ['template html', 'plan', 'content', 'design'],
    outputs: ['template riempito'],
    systemPromptPreview: 'Sostituisci tutti i placeholder {{...}} con i contenuti forniti, adattando colori e font al design.',
    filePath: 'lib/agents/html-agent.ts',
    enabled: true,
  },
  {
    name: 'seo',
    displayName: 'SEO Agent',
    description: 'Genera sitemap.xml, robots.txt, ottimizza meta tags, Open Graph, canonical URLs.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'modifier',
    inputs: ['messages', 'pages', 'custom domain', 'context'],
    outputs: ['seo files + page edits'],
    systemPromptPreview: 'Ottimizza l\'aspetto SEO del sito: meta, sitemap, robots, schema.org, OG tags.',
    filePath: 'lib/agents/seo-agent.ts',
    enabled: true,
  },
  {
    name: 'design-update',
    displayName: 'Design Update Agent',
    description: 'Modifica solo aspetti di design (colori, font, tema) lasciando i contenuti invariati.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 8192,
    category: 'modifier',
    inputs: ['user request', 'pages attuali', 'context'],
    outputs: ['pages con design aggiornato'],
    systemPromptPreview: 'Cambia esclusivamente CSS/colori/tipografia senza modificare il testo del sito.',
    filePath: 'lib/agents/design-agent.ts',
    enabled: true,
  },
  {
    name: 'content-update',
    displayName: 'Content Update Agent',
    description: 'Riscrive i testi con tone of voice diverso o traduce, mantenendo il design invariato.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 8192,
    category: 'modifier',
    inputs: ['user request', 'pages attuali', 'context'],
    outputs: ['pages con testi aggiornati'],
    systemPromptPreview: 'Modifica solo i testi delle pagine secondo le istruzioni utente (tone, traduzione).',
    filePath: 'lib/agents/content-agent.ts',
    enabled: true,
  },
  {
    name: 'site-analyzer',
    displayName: 'Site Analyzer',
    description: 'Analizza siti web esterni forniti come ispirazione, estrae design brief.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 2048,
    category: 'utility',
    inputs: ['URL'],
    outputs: ['DesignBrief'],
    systemPromptPreview: 'Visita un sito esterno e produci un brief sintetico (palette, tipografia, layout) usabile come ispirazione.',
    filePath: 'lib/agents/site-analyzer.ts',
    enabled: true,
  },
  {
    name: 'images',
    displayName: 'Images Agent',
    description: 'Ottimizza il markup delle immagini: alt text descrittivi, loading=lazy, srcset.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'utility',
    inputs: ['page html', 'business type'],
    outputs: ['edits find/replace per img'],
    systemPromptPreview: 'Migliora <img> aggiungendo alt SEO, loading=lazy, width/height. Non modificare src.',
    filePath: 'lib/agents/images-agent.ts',
    enabled: true,
  },
  {
    name: 'accessibility',
    displayName: 'Accessibility Agent',
    description: 'Audit e correzioni accessibilità (WCAG): aria-labels, contrasto, struttura semantica.',
    model: 'claude-haiku-4-5-20251001',
    maxTokens: 4096,
    category: 'utility',
    inputs: ['page html'],
    outputs: ['edits per accessibility fixes'],
    systemPromptPreview: 'Audit WCAG: aggiungi aria-*, fix headings, contrasto, struttura semantica.',
    filePath: 'lib/agents/accessibility-agent.ts',
    enabled: true,
  },
]

export const PIPELINE_FLOW = [
  { id: 'memory', label: 'Memory', column: 0, row: 0 },
  { id: 'planner', label: 'Planner', column: 1, row: 0 },
  { id: 'site-analyzer', label: 'Site Analyzer\n(se URL)', column: 1, row: 1, optional: true },
  { id: 'content', label: 'Content', column: 2, row: 0 },
  { id: 'design', label: 'Design', column: 2, row: 1 },
  { id: 'html', label: 'HTML', column: 3, row: 0 },
] as const

export const PIPELINE_EDGES = [
  { from: 'memory', to: 'planner' },
  { from: 'planner', to: 'content' },
  { from: 'planner', to: 'design' },
  { from: 'site-analyzer', to: 'design' },
  { from: 'content', to: 'html' },
  { from: 'design', to: 'html' },
] as const
